// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScCSWyoVeiQd7NJqyzjzAkRA7nvXZMgk',
    appId: '1:239748318084:web:74c51387ad31df4d6dd3d1',
    messagingSenderId: '239748318084',
    projectId: 'kasir-firebase-7a0ed',
    authDomain: 'kasir-firebase-7a0ed.firebaseapp.com',
    storageBucket: 'kasir-firebase-7a0ed.appspot.com',
    measurementId: 'G-83VDQQXB3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6iC4hj4-B_XmgpYy0RRcRNk6zqXtFAmw',
    appId: '1:239748318084:android:8ef5ffd09fbd2fdf6dd3d1',
    messagingSenderId: '239748318084',
    projectId: 'kasir-firebase-7a0ed',
    storageBucket: 'kasir-firebase-7a0ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilVwO2mfkFcAhT2ySdClVeK6j8KvkLJs',
    appId: '1:239748318084:ios:cf6e96fa31277fd06dd3d1',
    messagingSenderId: '239748318084',
    projectId: 'kasir-firebase-7a0ed',
    storageBucket: 'kasir-firebase-7a0ed.appspot.com',
    iosClientId: '239748318084-foh1bsk8tg8s3bfim0hfqmansbvf3bna.apps.googleusercontent.com',
    iosBundleId: 'com.pembuatanprogram.kantin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilVwO2mfkFcAhT2ySdClVeK6j8KvkLJs',
    appId: '1:239748318084:ios:cf6e96fa31277fd06dd3d1',
    messagingSenderId: '239748318084',
    projectId: 'kasir-firebase-7a0ed',
    storageBucket: 'kasir-firebase-7a0ed.appspot.com',
    iosClientId: '239748318084-foh1bsk8tg8s3bfim0hfqmansbvf3bna.apps.googleusercontent.com',
    iosBundleId: 'com.pembuatanprogram.kantin',
  );
}
